### PR TITLE
Install Application Permission

### PR DESCRIPTION
**Pull request by slartus**

### CODE REVIEW

**Comment by Alex009** [comment]
this permission looks platform specific (it works only for android), so i don't think that we should add this permission in common. users will be misleading by this API

**Comment by slartus** [comment]
> this permission looks platform specific (it works only for android), so i don't think that we should add this permission in common. users will be misleading by this API

like  Permission.STORAGE, Permission.WRITE_STORAGE

**Comment by Alex009** [comment]
> like Permission.STORAGE, Permission.WRITE_STORAGE

in case of this permissions we just not should additionally request permissions for this usecases on ios. but Install of apps is just not exist on iOS platform at all. so when we will see in common code that we request permission to install apps we will think that iOS can install apps someway. but it can't

**Comment by slartus** [comment]
> > like Permission.STORAGE, Permission.WRITE_STORAGE
> 
> in case of this permissions we just not should additionally request permissions for this usecases on ios. but Install of apps is just not exist on iOS platform at all. so when we will see in common code that we request permission to install apps we will think that iOS can install apps someway. but it can't

accepted

**Pull request closed without merging**
