### PR TITLE
Add POST_NOTIFICATION permission for Android 13+

### PR DESCRIPTION
**Pull request by Hash3690**
Hello !
[issue link](https://github.com/icerockdev/moko-permissions/issues/57)
I added the POST_NOTIFICATION permission for Android 13+.
I tested it with the sample app and it works great.
Thank you for this project !

### CODE REVIEW

**Comment by charles-buildingcash** [comment]
@Alex009 do not hesitate if you have any suggestions for improvements!

**Comment by petarmarijanovicfive** [comment]
This looks fine. Can it be merged?

**Comment by Hash3690** [comment]
Hey ! Can it be merged ? Are is there something to add ?

**Comment by dnikolic98** [comment]
This looks good, IMO it can be merged 🚀

**Review by Alex009 — APPROVED** [review]

**Pull request merged**
